version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-scripts/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  # pgadmin:  
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: hello@hello.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   ports:
  #     - "5050:80"
  #   volumes:
  #     - ./config/servers.json:/pgadmin4/servers.json:ro
    

networks:
  default:
    external:
      name: testnet